version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-flask-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: digital_college
    volumes:
      - sql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask:
    build: .
    container_name: flask-container
    restart: on-failure
    
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: digital_college
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
volumes:
  sql_data:     